services:
  # Web应用服务
  web:
    build: .
    container_name: cloudfare-qq-mail-web
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=518107qW
      - DB_NAME=cloudfare_qq_mail
      - FLASK_ENV=production
    volumes:
      - ./uploads:/app/uploads
      - ./temp_attachments:/app/temp_attachments
      - ./received_emails:/app/received_emails
    restart: unless-stopped
    networks:
      - app-network

  # MySQL数据库服务
  db:
    image: mysql:8.0
    container_name: cloudfare-qq-mail-db
    environment:
      MYSQL_ROOT_PASSWORD: 518107qW
      MYSQL_DATABASE: cloudfare_qq_mail
      MYSQL_CHARACTER_SET_SERVER: utf8mb4
      MYSQL_COLLATION_SERVER: utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password

  # phpMyAdmin (可选，用于数据库管理)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: cloudfare-qq-mail-phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: 518107qW
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - app-network

# 数据卷
volumes:
  mysql_data:
    driver: local

# 网络
networks:
  app-network:
    driver: bridge
